version: 2
jobs:
  test:
    docker:
      - image: circleci/node:current-browsers-legacy
    steps:
      - checkout
      - run:
          name: Make Report Directory
          command: mkdir report
      - run:
          name: Download Selenium Standalone Server
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium Standalone Server
          command: java -jar selenium-server-standalone-3.5.3.jar -log report/selenium.log
          background: true
      - run:
          name: Install Node Modules
          command: npm ci
      - run:
          name: Test to check DSL calculator functionality
          command: npx wdio wdio.conf.js --spec dslcalculator.js
      - run:
          name: Test to check DSL calculator functionality full tariff load
          command: npx wdio wdio.conf.js --spec dslcalculatorloadalltariff.js
      - run:
          name: Running test for checking streets for given post code API
          command: npx wdio wdio.conf.js --spec streetsfrompostcode.js
      - run:
          name: Running test for checking Cities for given post code API
          command: npx wdio wdio.conf.js --spec citiesfrompostcodeapi.js
      - store_test_results:
          path: Report
workflows:
  version: 2
  test:
    jobs:
      - test
